/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.cabolabs.openehr.rest.client

import spock.lang.Specification

class OpenEhrRestClientTest extends Specification {
    def "create ehr no payload"() {
        setup:
        def client = new OpenEhrRestClient("http://localhost:8090/openehr/v1", "http://localhost:8090/rest/v1")

        when:
        //
        client.auth("admin@cabolabs.com", "admin")
        def ehr = client.createEhr()

        then:
        true == true
    }
}
